name: cropadvisor
description: AI-powered crop advisory mobile application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.0.5
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  tflite_flutter: ^0.10.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  flutter_gen: ^5.11.0
  flutter_dotenv: ^5.1.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/.env
    #- assets/images/
